services:
  - type: web
    name: voicebillingai
    env: python
    region: singapore
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python -c "from db import init_db; init_db()" && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MERCHANT_UPI_ID
        value: merchant@upi
